name: 'Nuget package'
description: 'Build and Deploy a .net library on nuget'
inputs:
  version:
    description: 'Build version. Ex : 1.1.0'
    required: true
    default: '0.0.0'
  prefix:
    description: 'Build version prefix. Ex : -preview-31'
    default: ''
  workingDirectory:
    description: 'Working directory that contains the source folder'
    default: 'src'
  dotnet-version:
    description: 'Dotnet versions.'
    default: |
      7.0.x
      8.0.x
    type: string
runs:
  using: "composite"
  steps:
  # Show informations :
  - name: Setup .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
  - name: Restore dependencies
    shell: pwsh
    run: dotnet restore
    working-directory: src
  - name: Build and analyze
    shell: pwsh
    run: |
      echo "Build version : ${{ inputs.version }}${{ inputs.prefix }}"
      dotnet build --configuration Release --no-restore -p:FileVersion=${{ inputs.version }} /p:Version=${{ inputs.version }}${{ inputs.prefix }}
    working-directory: ${{ inputs.workingDirectory }}
  #- name: Launch unit tests
  #  run: dotnet test --configuration Release --no-build --verbosity normal /p:CollectCoverage=true  /p:CoverletOutputFormat=opencover --collect:"Code Coverage" /p:CoverletOutput="../sonarqubecoverage"
  #  working-directory: src