name: 'Nuget package version'
description: 'Find and generate the version of the nuget package to build'
inputs:
  nugetPackageIdentifier:
    description: 'Package identifier that should be used to check for version'
    required: true
    default: 'World'
outputs:
  build-version:
    description: 'Generated build version'
    value: ${{ steps.generate-version.outputs.build-version }}
  build-version-prefix:
    description: 'Generated build version prefix'
    value: ${{ steps.generate-version-prefix.outputs.build-version-prefix }}
runs:
  using: "composite"
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: |
        7.0.x
        8.0.x
  - name: Generate package version
    id: generate-version
    shell: pwsh
    run: |
      $version = .\scripts\generateVersion.ps1 -query ${{ inputs.nugetPackageIdentifier }}
      echo "build-version=$(echo $version)" >> $GITHUB_OUTPUT
      echo "Build version : $version"
    working-directory: ${{ github.action_path }}
  - name: Generate package version prefix
    id: generate-version-prefix
    shell: pwsh
    run: |
      $versionPrefix = ""
      if('${{ github.ref }}' -eq 'refs/heads/main')
      { 
        $versionPrefix = "" 
      }
      else { 
        $gitrunNumber = ${{ github.run_number }}
        $formattedGitrunNumber = "{0:D3}" -f $gitrunNumber
        $versionPrefix = "-preview-" + $formattedGitrunNumber 
      }
      echo "build-version-prefix=$(echo $versionPrefix)" >> $GITHUB_OUTPUT
      echo "Build version prefix: $versionPrefix"